"""initial migration

Revision ID: e4f6843e6c53
Revises: 
Create Date: 2025-09-09 16:46:33.583092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f6843e6c53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subjects', sa.JSON(), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('study_time', sa.JSON(), nullable=True),
    sa.Column('session_length', sa.JSON(), nullable=True),
    sa.Column('study_style', sa.JSON(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
